export type MonitorLanguage = 'en' | 'zh';
const en = {
  fullscreen: 'Expand camera preview',
  appFullscreen: 'Fullscreen app',
  exitFullscreen: 'Exit fullscreen',
  backgroundHint:
    'Keep this page visible beside your work. Monitoring pauses when the page is hidden; resume when you return.',
  title: 'Posture Monitor',
  subtitle: 'A little awareness. A more comfortable workday.',
  studio: 'Movement Studio',
  eyebrow: 'YOUR DESK, YOUR REFERENCE',
  heading: 'Make space for better habits.',
  intro:
    'Settle in, calibrate your camera, and let gentle reminders bring you back to the moment.',
  private: 'Processed on your device',
  language: 'Language',
  cameraProfile: 'Camera placement',
  front: 'Front view',
  side: 'Side view',
  diagonal: 'Diagonal view',
  frontHint:
    'Camera in front of you, near your screen. Keep your head and both shoulders visible.',
  sideHint:
    'Camera beside you. Keep the nearer ear and shoulder visible; include your hip for torso checks.',
  diagonalHint:
    'Camera at your front-left or front-right, about 30–45° off center. Continue facing your monitor.',
  left: 'Your left',
  right: 'Your right',
  cameraSide: 'Camera is on',
  settings: 'Settings',
  guide: 'Setup guide',
  calibration: 'Personal reference',
  calibrationTitle: 'Calibration required',
  calibrationHint:
    'Face your screen and hold still for 3 seconds to capture a reference.',
  stepOne: 'Keep the camera upright and steady.',
  stepTwo: 'Make sure your face and shoulders are visible.',
  stepThree: 'Include your hips for torso monitoring.',
  calibrate: 'Calibrate & start',
  recalibrate: 'Recalibrate',
  calibrating: 'Capturing your reference…',
  stable: 'Stay still for a moment.',
  unstable: 'Movement detected. Let’s hold still again.',
  referenceReady: 'Reference captured',
  referenceHint: 'Recalibrate after moving the camera or changing your setup.',
  noCamera: 'Camera preview',
  noCameraHint: 'Enable the camera, then calibrate.',
  enableCamera: 'Enable camera',
  stopCamera: 'Turn camera off',
  camera: 'Camera',
  cameraOff: 'Camera off',
  cameraOn: 'Camera on',
  cameraDevice: 'Choose webcam',
  defaultCamera: 'Default webcam',
  loading: 'Preparing pose tracking…',
  ready: 'Upper body in frame',
  finding: 'Adjust your framing',
  cameraDenied:
    'Camera access was denied. Allow camera access in your browser, then try again.',
  cameraTrouble:
    'Could not start tracking. Check your camera connection and browser permission, then try again.',
  needCamera: 'Enable your camera to get started.',
  needFrame:
    'Keep your face and the required shoulder landmarks visible. Feet and wrists are not required.',
  unavailable: 'Unavailable',
  waiting: 'Awaiting reference',
  near: 'Near reference',
  changed: 'Position changed',
  viewLimited: 'Some measurements are unavailable in this view.',
  head: 'Head position',
  torso: 'Torso lean',
  shoulders: 'Shoulder alignment',
  proximity: 'Camera proximity',
  headFrontDetail:
    'Change in the line between your ears compared with calibration. This describes lateral head tilt in the image.',
  headSideDetail:
    'Change in the line from your nearer shoulder to your ear compared with calibration. This is a projected position change, not a measured neck angle.',
  torsoDetail:
    'Change in the shoulder-to-hip line. If your hip is hidden by the desk or outside the frame, this check is unavailable.',
  shouldersDetail:
    'Change in the line between your shoulders. This check is used only in front view, where both shoulders are visible.',
  proximityDetail:
    'Change in apparent head size relative to calibration. It is not screen distance in centimeters. The check pauses when the perspective cross-check is unavailable or changes too much.',
  headCue:
    'Your head position has shifted. Take a moment to settle into a comfortable position.',
  torsoCue:
    'Your torso has leaned away from your reference. Shift or readjust when comfortable.',
  shouldersCue:
    'Your shoulder alignment has changed. Relax and readjust your position.',
  proximityCue:
    'You appear closer to the camera. Check your viewing distance and settle back if comfortable.',
  allNear: 'Your visible measurements are near your reference.',
  monitorReady: 'Your reference is ready. Monitoring has started.',
  reminders: 'Reminders',
  remindersHint: 'Notify after sustained changes.',
  remindersOff: 'Reminders off',
  reminder: 'Posture change detected',
  snooze: 'Snooze 5 min',
  snoozed: 'Reminders snoozed',
  wake: 'Resume reminders',
  pause: 'Pause monitoring',
  resume: 'Resume monitoring',
  paused: 'Monitoring paused',
  finish: 'Finish session',
  session: 'This session',
  monitoring: 'Monitoring',
  duration: 'Monitored time',
  referenceTime: 'Time near reference',
  coverage: 'Tracking coverage',
  gapTime: 'Tracking gaps',
  reminderCount: 'Reminders sent',
  timeHint:
    'Paused time is excluded. Time without every calibrated measurement is recorded as a tracking gap.',
  gapHint:
    'Missing landmarks, a turned face, or a changing camera view can suspend measurements. Gaps are not counted as posture problems.',
  threshold: 'Reminder threshold',
  currentChange: 'Current change',
  degree: '° change',
  scale: '% apparent size',
  sustained: 'Continuous change before reminding',
  cooldown: 'Minimum time between reminders',
  seconds: 'seconds',
  diagonalGrace:
    'Diagonal view always waits at least 8 seconds to reduce reminders during ordinary turning or reaching.',
  flexibility: 'Sensitivity',
  standard: 'Standard',
  gentle: 'Gentle',
  relaxed: 'Relaxed',
  overlay: 'Skeleton overlay',
  tweening: 'Smooth skeleton movement',
  tweenHint:
    'Optional movement smoothing; disabled by default. Measurements use the original landmarks.',
  mirror: 'Mirror preview',
  voice: 'Spoken reminders',
  voiceHint: 'Uses your browser’s available voices.',
  checks: 'Reminder types',
  history: 'Session history',
  historyHint:
    'Separate from your exercise history. Saved only in this browser.',
  noHistory: 'Your desk sessions will appear here.',
  summary: 'Session summary',
  summaryHint: 'A summary of your seated monitoring session.',
  download: 'Download summary',
  done: 'Done',
  events: 'Reminder moments',
  noEvents: 'No reminders were sent during this session.',
  stored: 'Stored on this device',
  storageError:
    'Browser storage is unavailable. This summary may not remain after closing the page.',
  cameraChanged:
    'The camera framing changed. Capture a new reference before continuing.',
  finishFirst:
    'Changing camera placement ends the current session and clears its reference.',
  guideTitle: 'Set up your seated workspace.',
  guideIntro:
    'Choose the profile that matches your actual webcam placement. These checks describe visible changes relative to your own reference.',
  guideFront:
    'Front: place the camera near your monitor and keep both sides of your face and both shoulders visible.',
  guideSide:
    'Side: place the camera to your left or right. Select that side so the nearer ear, shoulder, and optional hip are used.',
  guideDiagonal:
    'Diagonal: place the camera at the front-left or front-right, roughly 30–45° away from the screen direction. Keep facing the monitor and keep the camera upright.',
  guideChair:
    'Manual setup check: adjust your chair, back support, screen, and foot position for comfort. The camera does not establish chair support or weight distribution.',
  guideLimits:
    'A reference is a position you choose, not a medical assessment. Neck points are visual estimates; this app does not measure spinal curvature or diagnose posture.',
  guideBreak:
    'Move and change position when comfortable. The aim is awareness, not remaining perfectly still all day.',
  seated: 'SEATED WORKSPACE',
  chooseProfile: '01 / CAMERA PLACEMENT',
  privacyFooter:
    'Video stays on your device. Only session summaries are saved.',
  recheck: 'Capture a new reference whenever you move the webcam.',
  endNoData: 'No monitored time to save yet.',
  setupOnly: 'Visual guidance only',
} as const;
const zh: Record<keyof typeof en, string> = {
  fullscreen: '放大鏡頭預覽',
  appFullscreen: '全螢幕應用程式',
  exitFullscreen: '離開全螢幕',
  backgroundHint:
    '請將此頁面保持可見，例如放在工作視窗旁。頁面隱藏時監測會暫停，返回後請手動恢復。',
  title: '坐姿監測',
  subtitle: '多一點覺察，工作更自在。',
  studio: '運動工作室',
  eyebrow: '你的工作空間，你的參考姿勢',
  heading: '為舒適的習慣，留一點空間。',
  intro: '安坐、校準鏡頭，讓溫和提醒陪你照顧日常工作姿勢。',
  private: '在你的裝置上處理',
  language: '語言',
  cameraProfile: '鏡頭位置',
  front: '正面',
  side: '側面',
  diagonal: '斜前方',
  frontHint: '鏡頭置於螢幕附近、面向你。讓頭部和兩邊肩膀保持可見。',
  sideHint: '鏡頭置於身旁。讓靠近鏡頭的耳朵和肩膀可見；包含髖部即可監測軀幹。',
  diagonalHint: '鏡頭置於左前方或右前方，偏離正面約 30–45°。你仍然面向螢幕。',
  left: '你的左側',
  right: '你的右側',
  cameraSide: '鏡頭位於',
  settings: '設定',
  guide: '設定指南',
  calibration: '個人參考姿勢',
  calibrationTitle: '需要校準',
  calibrationHint: '面向螢幕並保持穩定 3 秒，記錄參考姿勢。',
  stepOne: '鏡頭保持端正、穩定。',
  stepTwo: '確保面部和所需肩膀關鍵點可見。',
  stepThree: '包含髖部即可監測軀幹。',
  calibrate: '校準並開始',
  recalibrate: '重新校準',
  calibrating: '正在記錄參考姿勢…',
  stable: '請保持穩定片刻。',
  unstable: '偵測到移動，請重新保持穩定。',
  referenceReady: '參考姿勢已記錄',
  referenceHint: '移動鏡頭或改變工作環境後，請重新校準。',
  noCamera: '鏡頭預覽',
  noCameraHint: '開啟鏡頭，然後校準。',
  enableCamera: '開啟鏡頭',
  stopCamera: '關閉鏡頭',
  camera: '鏡頭',
  cameraOff: '鏡頭已關閉',
  cameraOn: '鏡頭已開啟',
  cameraDevice: '選擇網絡攝影機',
  defaultCamera: '預設鏡頭',
  loading: '正在準備姿勢追蹤…',
  ready: '上半身已入鏡',
  finding: '請調整取景',
  cameraDenied: '未獲鏡頭使用權限。請在瀏覽器允許使用鏡頭，然後重試。',
  cameraTrouble: '未能開始追蹤。請檢查鏡頭連接及瀏覽器權限，然後重試。',
  needCamera: '請先開啟鏡頭。',
  needFrame: '讓面部和所需肩膀關鍵點保持可見。無須讓腳部和手腕入鏡。',
  unavailable: '暫時無法評估',
  waiting: '等待參考姿勢',
  near: '接近參考姿勢',
  changed: '姿勢有變化',
  viewLimited: '此視角暫時無法提供部分測量。',
  head: '頭部位置',
  torso: '軀幹傾斜',
  shoulders: '肩膀平衡',
  proximity: '與鏡頭的接近程度',
  headFrontDetail: '比較兩耳連線相對於校準時的變化，用來描述影像中的頭部側傾。',
  headSideDetail:
    '比較近側肩膀至耳朵連線相對於校準時的變化。這是影像投影位置的變化，並非實際頸部角度。',
  torsoDetail:
    '比較肩膀至髖部連線的變化。如髖部被桌子遮擋或不在畫面內，此項檢查會暫停。',
  shouldersDetail: '比較兩肩連線的變化。僅適用於正面視角，且兩肩均須可見。',
  proximityDetail:
    '比較頭部在畫面中的大小與校準時的差異，並非以厘米計算與螢幕的距離。當視角交叉檢查不可用或改變過多時，此項會暫停。',
  headCue: '頭部位置有變化，請稍作調整，回到舒適的位置。',
  torsoCue: '軀幹相對參考姿勢有所傾斜，可在舒適的情況下稍作調整。',
  shouldersCue: '肩膀平衡有所改變，試試放鬆並調整位置。',
  proximityCue:
    '你看來更靠近鏡頭了。請檢查觀看距離，並在舒適的情況下稍微後移。',
  allNear: '目前可見的測量均接近你的參考姿勢。',
  monitorReady: '參考姿勢已就緒，監測已開始。',
  reminders: '提醒',
  remindersHint: '持續偏移後發送通知。',
  remindersOff: '提醒已關閉',
  reminder: '偵測到姿勢變化',
  snooze: '暫停提醒 5 分鐘',
  snoozed: '提醒暫停中',
  wake: '恢復提醒',
  pause: '暫停監測',
  resume: '恢復監測',
  paused: '監測已暫停',
  finish: '結束監測',
  session: '本次監測',
  monitoring: '監測中',
  duration: '監測時間',
  referenceTime: '接近參考姿勢的時間',
  coverage: '追蹤覆蓋率',
  gapTime: '追蹤中斷時間',
  reminderCount: '已發送提醒',
  timeHint: '不包括暫停時間。未能取得所有已校準測量的時間，會記錄為追蹤中斷。',
  gapHint:
    '關鍵點被遮擋、轉頭或鏡頭視角改變，可能令測量暫停。這些中斷不會算作姿勢問題。',
  threshold: '提醒門檻',
  currentChange: '目前變化',
  degree: '° 變化',
  scale: '% 畫面大小',
  sustained: '持續變化多久才提醒',
  cooldown: '兩次提醒的最短間隔',
  seconds: '秒',
  diagonalGrace: '斜前方視角至少等待 8 秒，以減少日常轉身或伸手時的提醒。',
  flexibility: '敏感度',
  standard: '標準',
  gentle: '寬鬆',
  relaxed: '更寬鬆',
  overlay: '骨架疊圖',
  tweening: '平滑骨架動作',
  tweenHint: '可選的動作平滑功能，預設關閉。測量仍使用原始關鍵點。',
  mirror: '鏡像預覽',
  voice: '語音提醒',
  voiceHint: '使用瀏覽器提供的語音。',
  checks: '提醒類型',
  history: '監測紀錄',
  historyHint: '與運動紀錄分開，只儲存在此瀏覽器。',
  noHistory: '你的坐姿監測紀錄將顯示於此。',
  summary: '監測摘要',
  summaryHint: '本次坐姿監測的摘要。',
  download: '下載摘要',
  done: '完成',
  events: '提醒時刻',
  noEvents: '本次監測沒有發送提醒。',
  stored: '儲存在此裝置',
  storageError: '瀏覽器儲存功能無法使用。關閉頁面後，摘要可能不會保留。',
  cameraChanged: '鏡頭取景已改變，請重新記錄參考姿勢後繼續。',
  finishFirst: '更改鏡頭位置會結束本次監測並清除參考姿勢。',
  guideTitle: '設定你的坐姿工作空間。',
  guideIntro:
    '選擇符合實際鏡頭位置的視角。這些檢查描述的是相對於個人參考姿勢的可見變化。',
  guideFront: '正面：鏡頭置於螢幕附近，讓兩邊面部和肩膀均可見。',
  guideSide:
    '側面：鏡頭置於左側或右側。選擇對應方向，系統便會使用近側耳朵、肩膀及可見的髖部。',
  guideDiagonal:
    '斜前方：鏡頭置於左前方或右前方，與螢幕方向相差約 30–45°。你仍面向螢幕，鏡頭保持端正。',
  guideChair:
    '手動設定檢查：依舒適程度調整椅子、背部支撐、螢幕及雙腳位置。鏡頭無法確認椅子支撐或身體重量分佈。',
  guideLimits:
    '參考姿勢由你自行選擇，並非醫療評估。頸部關鍵點是視覺估計；本程式不會測量脊椎曲度或診斷姿勢。',
  guideBreak:
    '在舒適的情況下活動和變換姿勢。目的是增加覺察，不是整天保持完全靜止。',
  seated: '坐姿工作空間',
  chooseProfile: '01 / 鏡頭位置',
  privacyFooter: '影像留在你的裝置，只儲存監測摘要。',
  recheck: '每次移動鏡頭後，請重新記錄參考姿勢。',
  endNoData: '尚未有可儲存的監測時間。',
  setupOnly: '僅提供視覺指引',
};
export const monitorTranslations = { en, zh };
export type MonitorTextKey = keyof typeof en;
