import { translateFeedback } from '../catalog/feedback';
import type { StudioLanguage } from '../catalog';
export const studioZh: Record<string, string> = {
  'Camera access needs localhost or an HTTPS connection.':
    '使用攝影機需要 localhost 或 HTTPS 連線。',
  'Camera access was denied. Allow camera access in your browser and try again, or upload a video.':
    '攝影機權限被拒絕。請在瀏覽器允許使用攝影機後重試，或上載影片。',
  'No camera was found. Connect a camera or upload a video to get started.':
    '找不到攝影機。請連接攝影機或上載影片。',
  'Could not open the camera. Please try again.': '無法開啟攝影機，請重試。',
  'Please choose a video file, such as MP4, WebM, or MOV.':
    '請選擇影片檔案，例如 MP4、WebM 或 MOV。',
  'Choose a video smaller than 500 MB.': '請選擇小於 500 MB 的影片。',
  'This video could not be decoded. Try an MP4 (H.264) or WebM file supported by your browser.':
    '無法解碼此影片。請嘗試瀏覽器支援的 MP4（H.264）或 WebM 檔案。',
  'Tracking stopped. Reload the video or reconnect your camera.':
    '追蹤已停止，請重新載入影片或連接攝影機。',
  'Playback could not start. Try a different video.':
    '無法開始播放，請嘗試其他影片。',
  'Movement Studio': '動作工作室',
  'Movement studio': '動作工作室',
  'Main navigation': '主導覽',
  Practice: '練習',
  'Exercise library': '動作資料庫',
  'My progress': '我的進度',
  History: '歷史記錄',
  'Posture Monitor': '坐姿監測',
  'Setup guide': '設定指南',
  'Exit fullscreen': '離開全螢幕',
  'Fullscreen app': '全螢幕',
  Preferences: '偏好設定',
  'Studio mode': '工作室模式',
  'Guided practice': '引導練習',
  'Open analysis': '自由分析',
  Exercise: '動作',
  'Pose guide': '動作指南',
  'Input source': '輸入來源',
  'Live camera': '即時攝影機',
  'Upload video': '上載影片',
  'Expand preview': '放大預覽',
  'Loading model': '正在載入模型',
  'Body in frame': '身體在畫面內',
  'Body not in frame': '未能完整追蹤身體',
  'Camera off': '攝影機已關閉',
  'Tracking ready': '追蹤已就緒',
  'POSE TRACKING': '姿勢追蹤',
  'Live camera preview': '即時攝影機預覽',
  'Uploaded video preview': '影片預覽',
  'Body landmark overlay': '身體關鍵點顯示',
  'Camera preview': '攝影機預覽',
  'Video analysis': '影片分析',
  'Enable the camera with your full body in view.':
    '開啟攝影機，讓全身保持在畫面內。',
  'Choose or drop a video here.': '選擇或拖放影片至此處。',
  'Enable camera': '開啟攝影機',
  'Choose a video': '選擇影片',
  'Processed on your device': '在你的裝置上處理',
  'MP4, WebM or MOV · up to 500 MB · stays on your device':
    'MP4、WebM 或 MOV · 最大 500 MB · 保留於你的裝置',
  'Loading pose tracking…': '正在載入姿勢追蹤…',
  'Loading the pose model on your device.': '正在你的裝置上載入姿勢模型。',
  'Hold still for the countdown.': '倒數期間保持穩定。',
  Rest: '休息',
  'You’ve completed your': '你已完成',
  repetitions: '重複動作',
  hold: '保持姿勢',
  'Practice paused': '練習已暫停',
  'Resume practice': '繼續練習',
  'Keep your whole body in view': '讓全身保持在畫面內',
  'A full-body view works best': '全身入鏡效果最佳',
  'Pause video': '暫停影片',
  'Play video': '播放影片',
  'Video position': '影片位置',
  'Change video': '更換影片',
  'Skeleton overlay': '骨架顯示',
  'Mirror view': '鏡像顯示',
  'Voice cues': '語音提示',
  on: '開',
  off: '關',
  'SESSION IN PROGRESS': '課節進行中',
  'SESSION COMPLETE': '課節已完成',
  READY: '準備就緒',
  'Resume session': '繼續課節',
  'Pause session': '暫停課節',
  'Finish session': '結束課節',
  'Practice again': '再次練習',
  'Start guided session': '開始引導練習',
  'Start analysis': '開始分析',
  'Feedback is based on visible joint angles. A single camera cannot assess every aspect of a pose.':
    '回饋根據可見的關節角度。單一鏡頭無法評估姿勢的所有細節。',
  EXERCISE: '動作',
  ANALYZING: '正在分析',
  'View pose guide': '查看動作指南',
  Paused: '已暫停',
  'Target completed': '目標已完成',
  'Checks met': '符合檢查條件',
  'Adjustment needed': '需要調整',
  'Awaiting tracking': '等待追蹤',
  'Resume to continue measurements.': '繼續課節以恢復測量。',
  'Relax your arms, release the pose, and breathe.':
    '放鬆雙臂，離開姿勢並平穩呼吸。',
  'Enable the camera or load a video to see measurements.':
    '開啟攝影機或載入影片以查看測量結果。',
  'Alignment check': '姿勢檢查',
  LIVE: '即時',
  WAITING: '等待中',
  'Full body in frame': '全身在畫面內',
  'Standing leg extended': '站立腿伸展',
  'Controlled movement': '受控動作',
  'Steady, comfortable posture': '穩定舒適的姿勢',
  'Completed reps': '完成次數',
  'Aligned hold': '符合姿勢的時間',
  'A full controlled movement and return counts as one rep.':
    '完成一次受控動作並返回起始姿勢，計作一次。',
  'Only time with all alignment checks passing counts.':
    '僅計算符合所有姿勢檢查的時間。',
  Alignment: '姿勢符合度',
  'Visible checks met': '符合可見姿勢檢查',
  'Awaiting movement': '等待動作',
  'Video timeline': '影片時間軸',
  'Play during a session to analyze. Select a moment to revisit it.':
    '在課節期間播放以進行分析，選擇時間點可再次查看。',
  Aligned: '符合',
  Adjust: '調整',
  'Out of frame': '未能追蹤',
  '% checks met': '% 符合檢查',
  'Body out of frame': '未能完整追蹤身體',
  'Play during a session to analyze the video.':
    '在課節期間播放影片以進行分析。',
  exercises: '個動作',
  'Session history': '課節記錄',
  'Completed sessions': '完成課節',
  'Time in motion': '練習時間',
  min: '分鐘',
  'Aligned hold time': '符合姿勢的保持時間',
  'Completed repetitions': '完成動作次數',
  'Recent sessions': '最近課節',
  'Clear practice history?': '清除練習記錄？',
  'This removes all saved session summaries from this device.':
    '這會移除此裝置上所有已儲存的課節摘要。',
  'Clear history': '清除記錄',
  'Video review': '影片檢視',
  'No pose tracked': '未能追蹤姿勢',
  'No sessions yet': '尚無課節',
  'Complete your first session to see your progress here.':
    '完成第一個課節後，即可在此查看進度。',
  'Start practice': '開始練習',
  'Browser storage is unavailable. Your session is visible now, but may not be saved after this page closes.':
    '瀏覽器儲存空間無法使用。目前可查看課節，但關閉頁面後可能無法保留。',
  'Choose exercise video': '選擇動作影片',
  Done: '完成',
  'See the joints and connections we track.': '查看追蹤的關節及連線。',
  'Smooth skeleton movement': '平滑骨架移動',
  'Tween keypoints between tracked frames for a softer overlay.':
    '在追蹤畫格之間插補關鍵點，讓骨架顯示更平滑。',
  'Mirror camera': '鏡像攝影機',
  'Move as you would in a mirror.': '像照鏡子一樣移動。',
  'Spoken guidance': '語音指導',
  'Hear alignment cues while you move.': '移動時聆聽姿勢提示。',
  'Alignment flexibility': '姿勢容許幅度',
  'Allow a little more room in the joint-angle targets.':
    '容許關節角度目標有較大幅度。',
  'Standard · base angle ranges': '標準 · 基本角度範圍',
  'Gentle · 5° extra flexibility': '溫和 · 額外容許 5°',
  'Relaxed · 10° extra flexibility': '寬鬆 · 額外容許 10°',
  'Local processing': '本機處理',
  'Frames are processed in your browser. Forma does not upload or record your camera feed. Only session summaries are stored locally.':
    '畫面在瀏覽器內處理。Forma 不會上載或錄製攝影機畫面，只會在本機儲存課節摘要。',
  'Camera placement': '鏡頭位置',
  'Use a well-lit space. Place your camera around hip height and step back until your head, hands, and feet fit in the frame. Face the camera.':
    '選擇光線充足的空間，讓全身入鏡。請按動作指南使用正面或側面鏡頭。',
  'Practice modes': '練習模式',
  'Guided practice includes a framing countdown, an aligned hold or rep target, and a short rest. Open analysis lets you explore without a target or time limit.':
    '自動引導練習包含倒數、姿勢保持或次數目標及短暫休息。自由分析沒有目標限制。老師檢視的動作由老師確認完成。',
  'Alignment feedback': '姿勢回饋',
  'A visible movement and return counts even when an adjustment is needed. Holds count when all shape checks pass. Open Teacher measurements for the separate technique results.':
    '只要能追蹤完整動作及返回起點，即使姿勢需要調整也會計算次數。所有姿勢檢查符合時才計算保持時間。打開「老師測量資料」可查看另外記錄的姿勢結果。',
  'Feedback describes visible alignment from one camera. It isn’t a medical assessment. Move within a comfortable range and stop if something hurts.':
    '回饋只描述單一鏡頭可見的姿勢，並非醫療評估。請在舒適範圍內活動，如感到疼痛應停止。',
  'Session summary': '課節摘要',
  'Live practice': '即時練習',
  'Avg. alignment': '平均姿勢符合度',
  'Recorded cues': '已記錄提示',
  'No reliable pose was tracked. Try a brighter space with your whole body in view.':
    '未能可靠地追蹤姿勢。請嘗試在較明亮的空間讓全身入鏡。',
  'No adjustment cues recorded.': '沒有記錄到調整提示。',
  'Download session summary': '下載課節摘要',
};
export const translateStudio = (text: string, language: StudioLanguage) =>
  language === 'zh-Hant'
    ? (studioZh[text] ?? translateFeedback(text, language))
    : text;
